# Generated by Django 3.0.1 on 2021-02-08 09:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20210207_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotsize', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timeframe', models.CharField(blank=True, choices=[('1M', '1M'), ('5M', '5M'), ('15M', '15M'), ('30M', '30M'), ('H1', '1H'), ('4H', '4H')], max_length=4, null=True)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
