# Generated by Django 3.0.1 on 2021-02-11 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingdays', '0002_auto_20210208_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingday',
            name='date_created',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
